version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@mongodb-js/compass-collection"
    versions:
    - 2.0.7
